name: dev-merge
on:
  push:
    branches:
      - main
    paths:
      - platform/dev/**
      - modules/**
  workflow_dispatch: {}

jobs:
  apply:
    name: terraform apply dev
    uses: ./.github/workflows/merge-terraform-apply.yml
    with: 
      working_dir: platform/dev
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
